name: Hanuu, Sergeant
markdown: kramdown
theme: minimal-mistakes-jekyll
permalink: /blog/:year/:month/:day/:title
paginte: 7
paginate_path: "blog/page:num"
source 'https://rubygems.org'

highlighter: rouge