name: Hanuu, Sergeant
markdown: kramdown
theme: jekyll-theme-midnight
permalink: /blog/:year/:month/:day/:title
paginte: 7
paginate_path: "blog/page:num"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge